### PR TITLE
Included genericcc. Has Remy.

### PR DESCRIPTION
**Pull request by venkatarun95**
To run remy, 'placeholder-value' in remy.py needs to be replaced with the path to the rat file.

AIMD cannot yet be trusted because packet loss detection in genericcc is suspect. It seems to perform as expected though, but possible only because timeout is very low.

### CODE REVIEW

**Comment by keithw** [comment]
Hello Venkat,

Thanks -- please submit a mergeable pull request so that Travis-CI can run the automated tests.

Cheers,
Keith

**Comment by venkatarun95** [comment]
Pull request works for Remy.

(Realized this is a better place than an email.)

**Comment by keithw** [comment]
Merged! I temporarily pointed this to a local copy of the genericCC repo with one extra commit to make it compile on more recent GCCs. (And sent you a pull request.) If you're able to take that pull request, we'll redirect the submodule pointer back to your repo.

**Comment by venkatarun95** [comment]
Thanks! I have taken the pull request.

**Pull request closed without merging**
